version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.5

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # dogfood!
      - run: EVAL_IN_LEININGEN=1 lein eastwood

      # run tests!
      - run: lein test-all
